
DROP TABLE IF EXISTS PROP_POST;

CREATE TABLE PROP_POST (
  prop_Id INT AUTO_INCREMENT  PRIMARY KEY,
  locality VARCHAR(80) NOT NULL,   
  city  VARCHAR(50) NOT NULL,  
  sq_feet VARCHAR(50) NOT NULL,  
  htype VARCHAR(30) NOT NULL,   
  price INT NOT NULL, 
  owner_id INT  NOT NULL  
);

DROP TABLE IF EXISTS RENT_REQ;

CREATE TABLE RENT_REQ (
   req_Id INT AUTO_INCREMENT  PRIMARY KEY,  
   prop_id INT NOT NULL,
   owner_id INT  NOT NULL,
   owner_approval VARCHAR(30) NOT NULL,   
   requester_id INT NOT NULL,
   CONSTRAINT FK_RENT_REQ FOREIGN KEY(prop_id) REFERENCES PROP_POST(prop_id));
  
